package com.cocna.pdffilereader.common

enum class EventsBus {
    RELOAD_ALL_FILE,
    RELOAD_PDF_FILE,
    RELOAD_WORD_FILE,
    RELOAD_EXCEL_FILE,
    RELOAD_POWER_POINT_FILE,
    RELOAD_THEME,
    RELOAD_RECENT,
    RELOAD_FAVORITE,
    SHOW_ADS_BACK,
    PERMISSION_STORED_GRANTED
}